[package]
authors = ["Nelson Chen <nelson@mindflakes.com>"]
description = "Speedtest.net testing utility and crate"
exclude = ["tests/config/*"]
license = "MIT OR Apache-2.0"
name = "speedtest-rs"
repository = "https://github.com/nelsonjchen/speedtest-rs"
version = "0.0.13"
edition = "2018"

[dependencies]
clap = "2.33.0"
env_logger = "0.7.1"
log = "0.4.8"
time = "0.1.42"
url = "2.1.0"
xml-rs = "0.8.0"
mockito = "0.21.0"
md5 = "0.7.0"

[features]
rustls-tls = ["reqwest/rustls-tls"]

[dependencies.reqwest]
version= "0.10.1"
features = ["blocking", "gzip"]
